export type Skill = {
  value: string;
  label: string;
};

export const languages: Skill[] = [
  { value: "javascript", label: "JavaScript" },
  { value: "python", label: "Python" },
  { value: "java", label: "Java" },
  { value: "c++", label: "C++" },
  { value: "c#", label: "C#" },
  { value: "ruby", label: "Ruby" },
  { value: "php", label: "PHP" },
  { value: "swift", label: "Swift" },
  { value: "objective-c", label: "Objective-C" },
  { value: "typescript", label: "TypeScript" },
  { value: "go", label: "Go" },
  { value: "rust", label: "Rust" },
  { value: "r", label: "R" },
  { value: "perl", label: "Perl" },
  { value: "lua", label: "Lua" },
  { value: "shell", label: "Shell" },
  { value: "elixir", label: "Elixir" },
  { value: "erlang", label: "Erlang" },
  { value: "dart", label: "Dart" },
  { value: "julia", label: "Julia" },
  { value: "pascal", label: "Pascal" },
  { value: "ada", label: "Ada" },
  { value: "prolog", label: "Prolog" },
  { value: "hack", label: "Hack" },
  { value: "jscript", label: "JScript" },
  { value: "matlab", label: "MATLAB" },
  { value: "powershell", label: "PowerShell" },
  { value: "standard ml", label: "Standard ML" },
  { value: "turing", label: "Turing" },
  { value: "vbscript", label: "VBScript" },
  { value: "visual basic", label: "Visual Basic" },
  { value: "z shell", label: "Z shell" },
];

export const technical: Skill[] = [
  { value: "react", label: "React" },
  { value: "angular", label: "Angular" },
  { value: "vue", label: "Vue" },
  { value: "ember", label: "Ember" },
  { value: "backbone", label: "Backbone" },
  { value: "meteor", label: "Meteor" },
  { value: "polymer", label: "Polymer" },
  { value: "svelte", label: "Svelte" },
  { value: "preact", label: "Preact" },
  { value: "elm", label: "Elm" },
  { value: "nuxt", label: "Nuxt" },
  { value: "next", label: "Next" },
  { value: "react native", label: "React Native" },
  { value: "native script", label: "NativeScript" },
  { value: "flutter", label: "Flutter" },
  { value: "framework7", label: "Framework7" },
  { value: "jquery", label: "jQuery" },
  { value: "bootstrap", label: "Bootstrap" },
  { value: "mysql", label: "MySQL" },
  { value: "postgresql", label: "PostgreSQL" },
  { value: "sqlite", label: "SQLite" },
  { value: "mariadb", label: "MariaDB" },
  { value: "oracle", label: "Oracle" },
  { value: "sql server", label: "SQL Server" },
  { value: "mongodb", label: "MongoDB" },
  { value: "couchdb", label: "CouchDB" },
  { value: "cassandra", label: "Cassandra" },
  { value: "redis", label: "Redis" },
  { value: "firebase", label: "Firebase" },
];

export const speaks: Skill[] = [
  { value: "english", label: "English" },
  { value: "spanish", label: "Spanish" },
  { value: "french", label: "French" },
  { value: "german", label: "German" },
  { value: "hindi", label: "Hindi" },
  { value: "arabic", label: "Arabic" },
  { value: "japanese", label: "Japanese" },
  { value: "punjabi", label: "Punjabi" },
  { value: "telugu", label: "Telugu" },
  { value: "tamil", label: "Tamil" },
  { value: "kannada", label: "Kannada" },
  { value: "malayalam", label: "Malayalam" },
];

export const general: Skill[] = [
  { value: "collaboration", label: "Collaboration" },
  { value: "communication", label: "Communication" },
  { value: "problem solving", label: "Problem Solving" },
  { value: "adaptability", label: "Adaptability" },
  { value: "work ethic", label: "Work Ethic" },
  { value: "interpersonal skills", label: "Interpersonal Skills" },
  { value: "time management", label: "Time Management" },
  { value: "critical thinking", label: "Critical Thinking" },
  { value: "teamwork", label: "Teamwork" },
  { value: "creativity", label: "Creativity" },
  { value: "leadership", label: "Leadership" },
  { value: "attention to detail", label: "Attention to Detail" },
  { value: "customer service", label: "Customer Service" },
  { value: "organizational skills", label: "Organizational Skills" },
  { value: "emotional intelligence", label: "Emotional Intelligence" },
  { value: "conflict resolution", label: "Conflict Resolution" },
  { value: "decision making", label: "Decision Making" },
  { value: "negotiation", label: "Negotiation" },
  { value: "networking", label: "Networking" },
  { value: "public speaking", label: "Public Speaking" },
  { value: "research", label: "Research" },
  { value: "sales", label: "Sales" },
];
